<?php

use Illuminate\Database\Seeder;
use App\Kelurahan;

class KelurahanSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
      Kelurahan::insert([
        // ABIANSEMAL (BADUNG)
        array('kec_id' => 1, 'nama' => 'Abiansemal'),
        array('kec_id' => 1, 'nama' => 'Angantaka'),
        array('kec_id' => 1, 'nama' => 'Ayunan'),
        array('kec_id' => 1, 'nama' => 'Blahkiuh'),
        array('kec_id' => 1, 'nama' => 'Bongkasa'),
        array('kec_id' => 1, 'nama' => 'Bongkasa Pertiwi'),
        array('kec_id' => 1, 'nama' => 'Darmasaba'),
        array('kec_id' => 1, 'nama' => 'Dauh Yeh Cani'),
        array('kec_id' => 1, 'nama' => 'Jagapati'),
        array('kec_id' => 1, 'nama' => 'Mambal'),
        array('kec_id' => 1, 'nama' => 'Mekar Bhuwana'),
        array('kec_id' => 1, 'nama' => 'Punggul'),
        array('kec_id' => 1, 'nama' => 'Sangeh'),
        array('kec_id' => 1, 'nama' => 'Sedang'),
        array('kec_id' => 1, 'nama' => 'Selat'),
        array('kec_id' => 1, 'nama' => 'Sibang Gede'),
        array('kec_id' => 1, 'nama' => 'Sibang Kaja'),
        array('kec_id' => 1, 'nama' => 'Taman'),

        // KUTA (BADUNG)
        array('kec_id' => 2, 'nama' => 'Kedonganan'),
        array('kec_id' => 2, 'nama' => 'Kuta'),
        array('kec_id' => 2, 'nama' => 'Legian'),
        array('kec_id' => 2, 'nama' => 'Seminyak'),
        array('kec_id' => 2, 'nama' => 'Tuban'),

        // KUTA SELATAN (BADUNG)
        array('kec_id' => 3, 'nama' => 'Benoa'),
        array('kec_id' => 3, 'nama' => 'Jimbaran'),
        array('kec_id' => 3, 'nama' => 'Kutuh'),
        array('kec_id' => 3, 'nama' => 'Pecatu'),
        array('kec_id' => 3, 'nama' => 'Tanjung Benoa'),
        array('kec_id' => 3, 'nama' => 'Ungasan'),

        // KUTA UTARA (BADUNG)
        array('kec_id' => 4, 'nama' => 'Canggu'),
        array('kec_id' => 4, 'nama' => 'Dalung'),
        array('kec_id' => 4, 'nama' => 'Kerobokan'),
        array('kec_id' => 4, 'nama' => 'Kerobokan Kaja'),
        array('kec_id' => 4, 'nama' => 'Kerobokan Kelod'),
        array('kec_id' => 4, 'nama' => 'Tibubeneng'),

        // MENGWI (BADUNG)
        array('kec_id' => 5, 'nama' => 'Abianbase'),
        array('kec_id' => 5, 'nama' => 'Baha'),
        array('kec_id' => 5, 'nama' => 'Buduk'),
        array('kec_id' => 5, 'nama' => 'Cemagi'),
        array('kec_id' => 5, 'nama' => 'Gulingan'),
        array('kec_id' => 5, 'nama' => 'Kapal'),
        array('kec_id' => 5, 'nama' => 'Kekeran'),
        array('kec_id' => 5, 'nama' => 'Kuwum'),
        array('kec_id' => 5, 'nama' => 'Lukluk'),
        array('kec_id' => 5, 'nama' => 'Mengwi'),
        array('kec_id' => 5, 'nama' => 'Mengwitani'),
        array('kec_id' => 5, 'nama' => 'Munggu'),
        array('kec_id' => 5, 'nama' => 'Penarungan'),
        array('kec_id' => 5, 'nama' => 'Pererenan'),
        array('kec_id' => 5, 'nama' => 'Sading'),
        array('kec_id' => 5, 'nama' => 'Sembung'),
        array('kec_id' => 5, 'nama' => 'Sempidi'),
        array('kec_id' => 5, 'nama' => 'Sobangan'),
        array('kec_id' => 5, 'nama' => 'Tumbak Bayuh'),
        array('kec_id' => 5, 'nama' => 'Werdi Bhuawana'),

        // PETANG (BADUNG)
        array('kec_id' => 6, 'nama' => 'Belok'),
        array('kec_id' => 6, 'nama' => 'Carangsari'),
        array('kec_id' => 6, 'nama' => 'Getasan'),
        array('kec_id' => 6, 'nama' => 'Pangsan'),
        array('kec_id' => 6, 'nama' => 'Pelaga'),
        array('kec_id' => 6, 'nama' => 'Petang'),
        array('kec_id' => 6, 'nama' => 'Sulangai'),

        // BANGLI (BANGLI)
        array('kec_id' => 7, 'nama' => 'Bebalang'),
        array('kec_id' => 7, 'nama' => 'Bunutin'),
        array('kec_id' => 7, 'nama' => 'Cempaga'),
        array('kec_id' => 7, 'nama' => 'Kawan'),
        array('kec_id' => 7, 'nama' => 'Kayubihi'),
        array('kec_id' => 7, 'nama' => 'Kubu'),
        array('kec_id' => 7, 'nama' => 'Landih'),
        array('kec_id' => 7, 'nama' => 'Pengotan'),
        array('kec_id' => 7, 'nama' => 'Taman Bali'),

        // KINTAMANI (BANGLI)
        array('kec_id' => 8, 'nama' => 'Abang Songan'),
        array('kec_id' => 8, 'nama' => 'Abuan'),
        array('kec_id' => 8, 'nama' => 'Awan'),
        array('kec_id' => 8, 'nama' => 'Bantang'),
        array('kec_id' => 8, 'nama' => 'Banua'),
        array('kec_id' => 8, 'nama' => 'Batu Dinding'),
        array('kec_id' => 8, 'nama' => 'Batukaang'),
        array('kec_id' => 8, 'nama' => 'Batur Selatan'),
        array('kec_id' => 8, 'nama' => 'Batur Tengah'),
        array('kec_id' => 8, 'nama' => 'Batur Utara'),
        array('kec_id' => 8, 'nama' => 'Bayungcerik'),
        array('kec_id' => 8, 'nama' => 'Bayunggede'),
        array('kec_id' => 8, 'nama' => 'Belancan'),
        array('kec_id' => 8, 'nama' => 'Belandingan'),
        array('kec_id' => 8, 'nama' => 'Belanga'),
        array('kec_id' => 8, 'nama' => 'Belantih'),
        array('kec_id' => 8, 'nama' => 'Binyan'),
        array('kec_id' => 8, 'nama' => 'Bonyoh'),
        array('kec_id' => 8, 'nama' => 'Buahan'),
        array('kec_id' => 8, 'nama' => 'Bunutin'),
        array('kec_id' => 8, 'nama' => 'Catur'),
        array('kec_id' => 8, 'nama' => 'Daup'),
        array('kec_id' => 8, 'nama' => 'Dausa'),
        array('kec_id' => 8, 'nama' => 'Gunungbau'),
        array('kec_id' => 8, 'nama' => 'Katung'),
        array('kec_id' => 8, 'nama' => 'Kedisan'),
        array('kec_id' => 8, 'nama' => 'Kintamani'),
        array('kec_id' => 8, 'nama' => 'Kutuh'),
        array('kec_id' => 8, 'nama' => 'Langgahan'),
        array('kec_id' => 8, 'nama' => 'Lembean'),
        array('kec_id' => 8, 'nama' => 'Mangguh'),
        array('kec_id' => 8, 'nama' => 'Manikliyu'),
        array('kec_id' => 8, 'nama' => 'Mengani'),
        array('kec_id' => 8, 'nama' => 'Pengejaran'),
        array('kec_id' => 8, 'nama' => 'Pinggan'),
        array('kec_id' => 8, 'nama' => 'Satra'),
        array('kec_id' => 8, 'nama' => 'Sekaan'),
        array('kec_id' => 8, 'nama' => 'Sekardadi'),
        array('kec_id' => 8, 'nama' => 'Selulung'),
        array('kec_id' => 8, 'nama' => 'Serahi'),
        array('kec_id' => 8, 'nama' => 'Siyakin'),
        array('kec_id' => 8, 'nama' => 'Songan A'),
        array('kec_id' => 8, 'nama' => 'Songan B'),
        array('kec_id' => 8, 'nama' => 'Subaya'),
        array('kec_id' => 8, 'nama' => 'Sukawana'),
        array('kec_id' => 8, 'nama' => 'Suter'),
        array('kec_id' => 8, 'nama' => 'Terunyan'),
        array('kec_id' => 8, 'nama' => 'Ulian'),

        // SUSUT (BANGLI)
        array('kec_id' => 9, 'nama' => 'Abuan'),
        array('kec_id' => 9, 'nama' => 'Apuan'),
        array('kec_id' => 9, 'nama' => 'Demulih'),
        array('kec_id' => 9, 'nama' => 'Pengiangan'),
        array('kec_id' => 9, 'nama' => 'Penglumbaran'),
        array('kec_id' => 9, 'nama' => 'Selat'),
        array('kec_id' => 9, 'nama' => 'Sulahan'),
        array('kec_id' => 9, 'nama' => 'Susut'),
        array('kec_id' => 9, 'nama' => 'Tiga'),

        // TEMBUKU (BANGLI)
        array('kec_id' => 10, 'nama' => 'Bangbang'),
        array('kec_id' => 10, 'nama' => 'Jehem'),
        array('kec_id' => 10, 'nama' => 'Peninjoan'),
        array('kec_id' => 10, 'nama' => 'Tembuku'),
        array('kec_id' => 10, 'nama' => 'Undisan'),
        array('kec_id' => 10, 'nama' => 'Yangapi'),

        // BANJAR (BULELENG)
        array('kec_id' => 11, 'nama' => 'Banjar'),
        array('kec_id' => 11, 'nama' => 'Banjar Tegeha'),
        array('kec_id' => 11, 'nama' => 'Banyuatis'),
        array('kec_id' => 11, 'nama' => 'Banyusri'),
        array('kec_id' => 11, 'nama' => 'Cempaga'),
        array('kec_id' => 11, 'nama' => 'Dencarik'),
        array('kec_id' => 11, 'nama' => 'Gesing'),
        array('kec_id' => 11, 'nama' => 'Gobleg'),
        array('kec_id' => 11, 'nama' => 'Kaliasem'),
        array('kec_id' => 11, 'nama' => 'Kayuputih'),
        array('kec_id' => 11, 'nama' => 'Munduk'),
        array('kec_id' => 11, 'nama' => 'Pedawa'),
        array('kec_id' => 11, 'nama' => 'Sidetapa'),
        array('kec_id' => 11, 'nama' => 'Tampekan'),
        array('kec_id' => 11, 'nama' => 'Temukus'),
        array('kec_id' => 11, 'nama' => 'Tigawasa'),
        array('kec_id' => 11, 'nama' => 'Tirtasari'),

        // BULELENG (BULELENG)
        array('kec_id' => 12, 'nama' => 'Alasangker'),
        array('kec_id' => 12, 'nama' => 'Anturan'),
        array('kec_id' => 12, 'nama' => 'Astina'),
        array('kec_id' => 12, 'nama' => 'Banjar Bali'),
        array('kec_id' => 12, 'nama' => 'Banjar Jawa'),
        array('kec_id' => 12, 'nama' => 'Banjar Tegal'),
        array('kec_id' => 12, 'nama' => 'Banyuasri'),
        array('kec_id' => 12, 'nama' => 'Banyuning'),
        array('kec_id' => 12, 'nama' => 'Beratan'),
        array('kec_id' => 12, 'nama' => 'Bakti Seraga'),
        array('kec_id' => 12, 'nama' => 'Jinengdalem'),
        array('kec_id' => 12, 'nama' => 'Kalibukbuk'),
        array('kec_id' => 12, 'nama' => 'Kaliuntu'),
        array('kec_id' => 12, 'nama' => 'Kampung Anyar'),
        array('kec_id' => 12, 'nama' => 'Kampung Baru'),
        array('kec_id' => 12, 'nama' => 'Kampung Bugis'),
        array('kec_id' => 12, 'nama' => 'Kampung Kajanan'),
        array('kec_id' => 12, 'nama' => 'Kampung Singaraja'),
        array('kec_id' => 12, 'nama' => 'Kendran'),
        array('kec_id' => 12, 'nama' => 'Liligundi'),
        array('kec_id' => 12, 'nama' => 'Nagasepaha'),
        array('kec_id' => 12, 'nama' => 'Paket Agung'),
        array('kec_id' => 12, 'nama' => 'Pemaron'),
        array('kec_id' => 12, 'nama' => 'Penarukan'),
        array('kec_id' => 12, 'nama' => 'Penglatan'),
        array('kec_id' => 12, 'nama' => 'Petandakan'),
        array('kec_id' => 12, 'nama' => 'Poh Bergong'),
        array('kec_id' => 12, 'nama' => 'Sari Mekar'),
        array('kec_id' => 12, 'nama' => 'Tukadmungga'),

        // BUSUNGBIU (BULELENG)
        array('kec_id' => 13, 'nama' => 'Bengkel'),
        array('kec_id' => 13, 'nama' => 'Bongancina'),
        array('kec_id' => 13, 'nama' => 'Busungbiu'),
        array('kec_id' => 13, 'nama' => 'Kedis'),
        array('kec_id' => 13, 'nama' => 'Kekeran'),
        array('kec_id' => 13, 'nama' => 'Pelapuan'),
        array('kec_id' => 13, 'nama' => 'Pucaksari'),
        array('kec_id' => 13, 'nama' => 'Sepang'),
        array('kec_id' => 13, 'nama' => 'Sepang Kelod'),
        array('kec_id' => 13, 'nama' => 'Subuk'),
        array('kec_id' => 13, 'nama' => 'Telaga'),
        array('kec_id' => 13, 'nama' => 'Tinggarsari'),
        array('kec_id' => 13, 'nama' => 'Tista'),
        array('kec_id' => 13, 'nama' => 'Titab'),
        array('kec_id' => 13, 'nama' => 'Umejero'),

        // GEROKGAK (BULELENG)
        array('kec_id' => 14, 'nama' => 'Banyupoh'),
        array('kec_id' => 14, 'nama' => 'Celukan Bawang'),
        array('kec_id' => 14, 'nama' => 'Gerokgak'),
        array('kec_id' => 14, 'nama' => 'Musi'),
        array('kec_id' => 14, 'nama' => 'Patas'),
        array('kec_id' => 14, 'nama' => 'Pejarakan'),
        array('kec_id' => 14, 'nama' => 'Pemuteran'),
        array('kec_id' => 14, 'nama' => 'Pengulon'),
        array('kec_id' => 14, 'nama' => 'Penyabangan'),
        array('kec_id' => 14, 'nama' => 'Sanggalangit'),
        array('kec_id' => 14, 'nama' => 'Sumber Klampok'),
        array('kec_id' => 14, 'nama' => 'Sumberkima'),
        array('kec_id' => 14, 'nama' => 'Tinga Tinga'),
        array('kec_id' => 14, 'nama' => 'Tukad Sumaga'),

        // KUBUTAMBAHAN (BULELENG)
        array('kec_id' => 15, 'nama' => 'Bengkala'),
        array('kec_id' => 15, 'nama' => 'Bila'),
        array('kec_id' => 15, 'nama' => 'Bontihing'),
        array('kec_id' => 15, 'nama' => 'Bukti'),
        array('kec_id' => 15, 'nama' => 'Bulian'),
        array('kec_id' => 15, 'nama' => 'Depeha'),
        array('kec_id' => 15, 'nama' => 'Kubutambahan'),
        array('kec_id' => 15, 'nama' => 'Mengening'),
        array('kec_id' => 15, 'nama' => 'Pakisan'),
        array('kec_id' => 15, 'nama' => 'Tajun'),
        array('kec_id' => 15, 'nama' => 'Tambakan'),
        array('kec_id' => 15, 'nama' => 'Tamblang'),
        array('kec_id' => 15, 'nama' => 'Tunjung'),

        // SAWAN (BULELENG)
        array('kec_id' => 16, 'nama' => 'Bebetin'),
        array('kec_id' => 16, 'nama' => 'Bungkulan'),
        array('kec_id' => 16, 'nama' => 'Galungan'),
        array('kec_id' => 16, 'nama' => 'Giri Emas'),
        array('kec_id' => 16, 'nama' => 'Jagaraga'),
        array('kec_id' => 16, 'nama' => 'Kerobokan'),
        array('kec_id' => 16, 'nama' => 'Lemukih'),
        array('kec_id' => 16, 'nama' => 'Menyali'),
        array('kec_id' => 16, 'nama' => 'Sangsit'),
        array('kec_id' => 16, 'nama' => 'Sawan'),
        array('kec_id' => 16, 'nama' => 'Sekumpul'),
        array('kec_id' => 16, 'nama' => 'Sinabun'),
        array('kec_id' => 16, 'nama' => 'Sudaji'),
        array('kec_id' => 16, 'nama' => 'Suwug'),

        // SERIRIT (BULELENG)
        array('kec_id' => 17, 'nama' => 'Banjar Asem'),
        array('kec_id' => 17, 'nama' => 'Bestala'),
        array('kec_id' => 17, 'nama' => 'Bubunan'),
        array('kec_id' => 17, 'nama' => 'Gunungsari'),
        array('kec_id' => 17, 'nama' => 'Joanyar'),
        array('kec_id' => 17, 'nama' => 'Kalianget'),
        array('kec_id' => 17, 'nama' => 'Kalisada'),
        array('kec_id' => 17, 'nama' => 'Lokapaksa'),
        array('kec_id' => 17, 'nama' => 'Mayong'),
        array('kec_id' => 17, 'nama' => 'Munduk Bestala'),
        array('kec_id' => 17, 'nama' => 'Pangkungparuk'),
        array('kec_id' => 17, 'nama' => 'Patemon'),
        array('kec_id' => 17, 'nama' => 'Pengastulan'),
        array('kec_id' => 17, 'nama' => 'Rangdu'),
        array('kec_id' => 17, 'nama' => 'Ringdikit'),
        array('kec_id' => 17, 'nama' => 'Seririt'),
        array('kec_id' => 17, 'nama' => 'Sulanyah'),
        array('kec_id' => 17, 'nama' => 'Tangguwisia'),
        array('kec_id' => 17, 'nama' => 'Ularan'),
        array('kec_id' => 17, 'nama' => 'Umeanyar'),
        array('kec_id' => 17, 'nama' => 'Unggahan'),

        // SUKASADA (BULELENG)
        array('kec_id' => 18, 'nama' => 'Ambengan'),
        array('kec_id' => 18, 'nama' => 'Gitgit'),
        array('kec_id' => 18, 'nama' => 'Kayuputih'),
        array('kec_id' => 18, 'nama' => 'Padangbulia'),
        array('kec_id' => 18, 'nama' => 'Pancasari'),
        array('kec_id' => 18, 'nama' => 'Panji'),
        array('kec_id' => 18, 'nama' => 'Panji Anom'),
        array('kec_id' => 18, 'nama' => 'Pegadungan'),
        array('kec_id' => 18, 'nama' => 'Pegayaman'),
        array('kec_id' => 18, 'nama' => 'Sambangan'),
        array('kec_id' => 18, 'nama' => 'Selat'),
        array('kec_id' => 18, 'nama' => 'Silangjana'),
        array('kec_id' => 18, 'nama' => 'Sukasada'),
        array('kec_id' => 18, 'nama' => 'Tegal Linggah'),
        array('kec_id' => 18, 'nama' => 'Wanagiri'),

        // TEJAKULA (BULELENG)
        array('kec_id' => 19, 'nama' => 'Bondalem'),
        array('kec_id' => 19, 'nama' => 'Julah'),
        array('kec_id' => 19, 'nama' => 'Les'),
        array('kec_id' => 19, 'nama' => 'Madenan'),
        array('kec_id' => 19, 'nama' => 'Pacung'),
        array('kec_id' => 19, 'nama' => 'Penuktukan'),
        array('kec_id' => 19, 'nama' => 'Sambirenteng'),
        array('kec_id' => 19, 'nama' => 'Sembiran'),
        array('kec_id' => 19, 'nama' => 'Tejakula'),
        array('kec_id' => 19, 'nama' => 'Tembok'),

        // DENPASAR BARAT (DENPASAR)
        array('kec_id' => 20, 'nama' => 'Dauh Puri'),
        array('kec_id' => 20, 'nama' => 'Dauh Puri Kangin'),
        array('kec_id' => 20, 'nama' => 'Dauh Puri Kauh'),
        array('kec_id' => 20, 'nama' => 'Dauh Puri Kelod'),
        array('kec_id' => 20, 'nama' => 'Padangsambian'),
        array('kec_id' => 20, 'nama' => 'Padangsambian Kaja'),
        array('kec_id' => 20, 'nama' => 'Padangsambian Kelod'),
        array('kec_id' => 20, 'nama' => 'Pemecutan'),
        array('kec_id' => 20, 'nama' => 'Pemecutan Kelod'),
        array('kec_id' => 20, 'nama' => 'Tegal Harum'),
        array('kec_id' => 20, 'nama' => 'Tegal Kertha'),

        // DENPASAR SELATAN (DENPASAR)
        array('kec_id' => 21, 'nama' => 'Panjer'),
        array('kec_id' => 21, 'nama' => 'Pedungan'),
        array('kec_id' => 21, 'nama' => 'Pemogan'),
        array('kec_id' => 21, 'nama' => 'Renon'),
        array('kec_id' => 21, 'nama' => 'Sanur'),
        array('kec_id' => 21, 'nama' => 'Sanur Kaja'),
        array('kec_id' => 21, 'nama' => 'Sanur Kauh'),
        array('kec_id' => 21, 'nama' => 'Serangan'),
        array('kec_id' => 21, 'nama' => 'Sesetan'),
        array('kec_id' => 21, 'nama' => 'Sidakarya'),

        // DENPASAR TIMUR (DENPASAR)
        array('kec_id' => 22, 'nama' => 'Dangin Puri'),
        array('kec_id' => 22, 'nama' => 'Dangin Puri Klod'),
        array('kec_id' => 22, 'nama' => 'Kesiman'),
        array('kec_id' => 22, 'nama' => 'Kesiman Kertalangu'),
        array('kec_id' => 22, 'nama' => 'Kesiman Petilan'),
        array('kec_id' => 22, 'nama' => 'Penatih'),
        array('kec_id' => 22, 'nama' => 'Penatih Dangin Puri'),
        array('kec_id' => 22, 'nama' => 'Sumerta'),
        array('kec_id' => 22, 'nama' => 'Sumerta Kaja'),
        array('kec_id' => 22, 'nama' => 'Sumerta Kauh'),
        array('kec_id' => 22, 'nama' => 'Sumerta Kelod'),

        // DENPASAR UTARA (DENPASAR)
        array('kec_id' => 23, 'nama' => 'Dangin Puri Kaja'),
        array('kec_id' => 23, 'nama' => 'Dangin Puri Kangin'),
        array('kec_id' => 23, 'nama' => 'Dangin Puri Kauh'),
        array('kec_id' => 23, 'nama' => 'Dauh Puri Kaja'),
        array('kec_id' => 23, 'nama' => 'Peguyangan'),
        array('kec_id' => 23, 'nama' => 'Peguyangan Kaja'),
        array('kec_id' => 23, 'nama' => 'Peguyangan Kangin'),
        array('kec_id' => 23, 'nama' => 'Pemecutan Kaja'),
        array('kec_id' => 23, 'nama' => 'Tonja'),
        array('kec_id' => 23, 'nama' => 'Ubung'),
        array('kec_id' => 23, 'nama' => 'Ubung Kaja'),

        // BLAHBATUH (GIANYAR)
        array('kec_id' => 24, 'nama' => 'Bedulu'),
        array('kec_id' => 24, 'nama' => 'Belega'),
        array('kec_id' => 24, 'nama' => 'Blahbatuh'),
        array('kec_id' => 24, 'nama' => 'Bona'),
        array('kec_id' => 24, 'nama' => 'Buruan'),
        array('kec_id' => 24, 'nama' => 'Keramas'),
        array('kec_id' => 24, 'nama' => 'Medahan'),
        array('kec_id' => 24, 'nama' => 'Pering'),
        array('kec_id' => 24, 'nama' => 'Saba'),

        // GIANYAR (GIANYAR)
        array('kec_id' => 25, 'nama' => 'Abianbase'),
        array('kec_id' => 25, 'nama' => 'Bakbakan'),
        array('kec_id' => 25, 'nama' => 'Beng'),
        array('kec_id' => 25, 'nama' => 'Bitera'),
        array('kec_id' => 25, 'nama' => 'Gianyar'),
        array('kec_id' => 25, 'nama' => 'Lebih'),
        array('kec_id' => 25, 'nama' => 'Petak'),
        array('kec_id' => 25, 'nama' => 'Petak Kaja'),
        array('kec_id' => 25, 'nama' => 'Samplangan'),
        array('kec_id' => 25, 'nama' => 'Serongga'),
        array('kec_id' => 25, 'nama' => 'Siangan'),
        array('kec_id' => 25, 'nama' => 'Sidan'),
        array('kec_id' => 25, 'nama' => 'Sumita'),
        array('kec_id' => 25, 'nama' => 'Suwat'),
        array('kec_id' => 25, 'nama' => 'Tegal Tugu'),
        array('kec_id' => 25, 'nama' => 'Temesi'),
        array('kec_id' => 25, 'nama' => 'Tulikup'),

        // PAYANGAN (GIANYAR)
        array('kec_id' => 26, 'nama' => 'Bresela'),
        array('kec_id' => 26, 'nama' => 'Buahan'),
        array('kec_id' => 26, 'nama' => 'Buahan Kaja'),
        array('kec_id' => 26, 'nama' => 'Bukian'),
        array('kec_id' => 26, 'nama' => 'Kelusa'),
        array('kec_id' => 26, 'nama' => 'Kerta'),
        array('kec_id' => 26, 'nama' => 'Melinggih'),
        array('kec_id' => 26, 'nama' => 'Melinggih Kelod'),
        array('kec_id' => 26, 'nama' => 'Puhu'),

        // SUKAWATI (GIANYAR)
        array('kec_id' => 27, 'nama' => 'Batuan'),
        array('kec_id' => 27, 'nama' => 'Batuan Kaler'),
        array('kec_id' => 27, 'nama' => 'Batubulan'),
        array('kec_id' => 27, 'nama' => 'Batubulan Kangin'),
        array('kec_id' => 27, 'nama' => 'Celuk'),
        array('kec_id' => 27, 'nama' => 'Guwang'),
        array('kec_id' => 27, 'nama' => 'Kemenuh'),
        array('kec_id' => 27, 'nama' => 'Ketewel'),
        array('kec_id' => 27, 'nama' => 'Singapadu'),
        array('kec_id' => 27, 'nama' => 'Singapadu Kaler'),
        array('kec_id' => 27, 'nama' => 'Singapadu Tengah'),
        array('kec_id' => 27, 'nama' => 'Sukawati'),

        // TAMPAK SIRING (GIANYAR)
        array('kec_id' => 28, 'nama' => 'Manukaya'),
        array('kec_id' => 28, 'nama' => 'Pejeng'),
        array('kec_id' => 28, 'nama' => 'Pejeng Kaja'),
        array('kec_id' => 28, 'nama' => 'Pejeng Kangin'),
        array('kec_id' => 28, 'nama' => 'Pejeng Kawan'),
        array('kec_id' => 28, 'nama' => 'Pejeng Kelod'),
        array('kec_id' => 28, 'nama' => 'Sanding'),
        array('kec_id' => 28, 'nama' => 'Tampaksiring'),

        // TEGALLALANG (GIANYAR)
        array('kec_id' => 29, 'nama' => 'Kedisan'),
        array('kec_id' => 29, 'nama' => 'Keliki'),
        array('kec_id' => 29, 'nama' => 'Kenderan'),
        array('kec_id' => 29, 'nama' => 'Pupuan'),
        array('kec_id' => 29, 'nama' => 'Sebatu'),
        array('kec_id' => 29, 'nama' => 'Taro'),
        array('kec_id' => 29, 'nama' => 'Tegallalang'),

        // UBUD (GIANYAR)
        array('kec_id' => 30, 'nama' => 'Kedewatan'),
        array('kec_id' => 30, 'nama' => 'Lodtunduh'),
        array('kec_id' => 30, 'nama' => 'Mas'),
        array('kec_id' => 30, 'nama' => 'Peliatan'),
        array('kec_id' => 30, 'nama' => 'Petulu'),
        array('kec_id' => 30, 'nama' => 'Sayan'),
        array('kec_id' => 30, 'nama' => 'Singakerta'),
        array('kec_id' => 30, 'nama' => 'Ubud'),

        // JEMBRANA (JEMBRANA)
        array('kec_id' => 31, 'nama' => 'Air Kuning'),
        array('kec_id' => 31, 'nama' => 'Batuagung'),
        array('kec_id' => 31, 'nama' => 'Budeng'),
        array('kec_id' => 31, 'nama' => 'Dangin Tukadaya'),
        array('kec_id' => 31, 'nama' => 'Dauhwaru'),
        array('kec_id' => 31, 'nama' => 'Loloan Timur'),
        array('kec_id' => 31, 'nama' => 'Pendem'),
        array('kec_id' => 31, 'nama' => 'Perancak'),
        array('kec_id' => 31, 'nama' => 'Sangkaragung'),
        array('kec_id' => 31, 'nama' => 'Yeh Kuning'),

        // MELAYA (JEMBRANA)
        array('kec_id' => 32, 'nama' => 'Blimbingsari'),
        array('kec_id' => 32, 'nama' => 'Candikusuma'),
        array('kec_id' => 32, 'nama' => 'Ekasari'),
        array('kec_id' => 32, 'nama' => 'Gilimanuk'),
        array('kec_id' => 32, 'nama' => 'Manistutu'),
        array('kec_id' => 32, 'nama' => 'Melaya'),
        array('kec_id' => 32, 'nama' => 'Nusa Sari'),
        array('kec_id' => 32, 'nama' => 'Tukadaya'),
        array('kec_id' => 32, 'nama' => 'Tuwed'),
        array('kec_id' => 32, 'nama' => 'Warnasari'),

        // MENDOYO (JEMBRANA)
        array('kec_id' => 33, 'nama' => 'Delod Berawah'),
        array('kec_id' => 33, 'nama' => 'Mendoyo Dangin Tukad'),
        array('kec_id' => 33, 'nama' => 'Mendoyo Dauh Tukad'),
        array('kec_id' => 33, 'nama' => 'Penyaringan'),
        array('kec_id' => 33, 'nama' => 'Pergung'),
        array('kec_id' => 33, 'nama' => 'Pohsanten'),
        array('kec_id' => 33, 'nama' => 'Tegal Cangkring'),
        array('kec_id' => 33, 'nama' => 'Yeh Embang'),
        array('kec_id' => 33, 'nama' => 'Yeh Embang Kangin'),
        array('kec_id' => 33, 'nama' => 'Yeh Embang Kauh'),
        array('kec_id' => 33, 'nama' => 'Yeh Sumbul'),

        // NEGARA (JEMBRANA)
        array('kec_id' => 34, 'nama' => 'Baler Bale Agung'),
        array('kec_id' => 34, 'nama' => 'Baluk'),
        array('kec_id' => 34, 'nama' => 'Banjar Tengah'),
        array('kec_id' => 34, 'nama' => 'Banyubiru'),
        array('kec_id' => 34, 'nama' => 'Berangbang'),
        array('kec_id' => 34, 'nama' => 'Cupel'),
        array('kec_id' => 34, 'nama' => 'Kaliakah'),
        array('kec_id' => 34, 'nama' => 'Lelateng'),
        array('kec_id' => 34, 'nama' => 'Loloan Barat'),
        array('kec_id' => 34, 'nama' => 'Pengambengan'),
        array('kec_id' => 34, 'nama' => 'Tegal Badeng Barat'),
        array('kec_id' => 34, 'nama' => 'Tegal Badeng Timur'),

        // PEKUTATAN (JEMBRANA)
        array('kec_id' => 35, 'nama' => 'Asahduren'),
        array('kec_id' => 35, 'nama' => 'Gumbrih'),
        array('kec_id' => 35, 'nama' => 'Manggissari'),
        array('kec_id' => 35, 'nama' => 'Medewi'),
        array('kec_id' => 35, 'nama' => 'Pangyangan'),
        array('kec_id' => 35, 'nama' => 'Pekutatan'),
        array('kec_id' => 35, 'nama' => 'Pengeragoan'),
        array('kec_id' => 35, 'nama' => 'Pulukan'),

        // ABANG (KARANGASEM)
        array('kec_id' => 36, 'nama' => 'Ababi'),
        array('kec_id' => 36, 'nama' => 'Abang'),
        array('kec_id' => 36, 'nama' => 'Bunutan'),
        array('kec_id' => 36, 'nama' => 'Culik'),
        array('kec_id' => 36, 'nama' => 'Datah'),
        array('kec_id' => 36, 'nama' => 'Kerta Mandala'),
        array('kec_id' => 36, 'nama' => 'Kesimpar'),
        array('kec_id' => 36, 'nama' => 'Laba Sari'),
        array('kec_id' => 36, 'nama' => 'Nawakerti'),
        array('kec_id' => 36, 'nama' => 'Pidpid'),
        array('kec_id' => 36, 'nama' => 'Purwakerti'),
        array('kec_id' => 36, 'nama' => 'Tista'),
        array('kec_id' => 36, 'nama' => 'Tiyingtali'),
        array('kec_id' => 36, 'nama' => 'Tri Buana'),

        // BEBANDEM (KARANGASEM)
        array('kec_id' => 37, 'nama' => 'Bebandem'),
        array('kec_id' => 37, 'nama' => 'Buana Giri'),
        array('kec_id' => 37, 'nama' => 'Budakeling'),
        array('kec_id' => 37, 'nama' => 'Bungaya'),
        array('kec_id' => 37, 'nama' => 'Bungaya Kangin'),
        array('kec_id' => 37, 'nama' => 'Jungutan'),
        array('kec_id' => 37, 'nama' => 'Macang'),
        array('kec_id' => 37, 'nama' => 'Sibetan'),

        // KARANG ASEM (KARANGASEM)
        array('kec_id' => 38, 'nama' => 'Bugbug'),
        array('kec_id' => 38, 'nama' => 'Bukit'),
        array('kec_id' => 38, 'nama' => 'Karangasem'),
        array('kec_id' => 38, 'nama' => 'Padang Kerta'),
        array('kec_id' => 38, 'nama' => 'Pertima'),
        array('kec_id' => 38, 'nama' => 'Seraya Barat'),
        array('kec_id' => 38, 'nama' => 'Seraya Tengah'),
        array('kec_id' => 38, 'nama' => 'Seraya Timur'),
        array('kec_id' => 38, 'nama' => 'Subagan'),
        array('kec_id' => 38, 'nama' => 'Tegallinggah'),
        array('kec_id' => 38, 'nama' => 'Tumbu'),

        // KUBU (KARANGASEM)
        array('kec_id' => 39, 'nama' => 'Ban'),
        array('kec_id' => 39, 'nama' => 'Batu Ringgit'),
        array('kec_id' => 39, 'nama' => 'Dukuh'),
        array('kec_id' => 39, 'nama' => 'Kubu'),
        array('kec_id' => 39, 'nama' => 'Sukadana'),
        array('kec_id' => 39, 'nama' => 'Tianyar Barat'),
        array('kec_id' => 39, 'nama' => 'Tianyar Tengah'),
        array('kec_id' => 39, 'nama' => 'Tianyar Timur'),
        array('kec_id' => 39, 'nama' => 'Tulamben'),

        // MANGGIS (KARANGASEM)
        array('kec_id' => 40, 'nama' => 'Antiga'),
        array('kec_id' => 40, 'nama' => 'Antiga Kelod'),
        array('kec_id' => 40, 'nama' => 'Gegelang'),
        array('kec_id' => 40, 'nama' => 'Manggis'),
        array('kec_id' => 40, 'nama' => 'Ngis'),
        array('kec_id' => 40, 'nama' => 'Nyuh Tebel'),
        array('kec_id' => 40, 'nama' => 'Padangbai'),
        array('kec_id' => 40, 'nama' => 'Pesedahan'),
        array('kec_id' => 40, 'nama' => 'Selumbung'),
        array('kec_id' => 40, 'nama' => 'Sengkidu'),
        array('kec_id' => 40, 'nama' => 'Tenganan'),
        array('kec_id' => 40, 'nama' => 'Ulakan'),


        // RENDANG (KARANGASEM)
        array('kec_id' => 41, 'nama' => 'Besakih'),
        array('kec_id' => 41, 'nama' => 'Menanga'),
        array('kec_id' => 41, 'nama' => 'Nongan'),
        array('kec_id' => 41, 'nama' => 'Pempatan'),
        array('kec_id' => 41, 'nama' => 'Pesaban'),
        array('kec_id' => 41, 'nama' => 'Rendang'),

        // SELAT (KARANGASEM)
        array('kec_id' => 42, 'nama' => 'Amerta Bhuana'),
        array('kec_id' => 42, 'nama' => 'Duda'),
        array('kec_id' => 42, 'nama' => 'Duda Timur'),
        array('kec_id' => 42, 'nama' => 'Duda Utara'),
        array('kec_id' => 42, 'nama' => 'Muncan'),
        array('kec_id' => 42, 'nama' => 'Pering Sari'),
        array('kec_id' => 42, 'nama' => 'Sebudi'),
        array('kec_id' => 42, 'nama' => 'Selat'),

        // SIDEMEN (KARANGASEM)
        array('kec_id' => 43, 'nama' => 'Kertha Buana'),
        array('kec_id' => 43, 'nama' => 'Lokasari'),
        array('kec_id' => 43, 'nama' => 'Sangkan Gunung'),
        array('kec_id' => 43, 'nama' => 'Sidemen'),
        array('kec_id' => 43, 'nama' => 'Sindu Wati'),
        array('kec_id' => 43, 'nama' => 'Talibeng'),
        array('kec_id' => 43, 'nama' => 'Tangkup'),
        array('kec_id' => 43, 'nama' => 'Telaga Tawang'),
        array('kec_id' => 43, 'nama' => 'Tri Eka Buana'),
        array('kec_id' => 43, 'nama' => 'Wisma Kerta'),

        // BANJARANGKAN (KLUNGKUNG)
        array('kec_id' => 44, 'nama' => 'Aan'),
        array('kec_id' => 44, 'nama' => 'Bakas'),
        array('kec_id' => 44, 'nama' => 'Banjarangkan'),
        array('kec_id' => 44, 'nama' => 'Bungbungan'),
        array('kec_id' => 44, 'nama' => 'Getakan'),
        array('kec_id' => 44, 'nama' => 'Negari'),
        array('kec_id' => 44, 'nama' => 'Nyalian'),
        array('kec_id' => 44, 'nama' => 'Nyanglan'),
        array('kec_id' => 44, 'nama' => 'Takmung'),
        array('kec_id' => 44, 'nama' => 'Tihingan'),
        array('kec_id' => 44, 'nama' => 'Timuhun'),
        array('kec_id' => 44, 'nama' => 'Tohpati'),
        array('kec_id' => 44, 'nama' => 'Tusan'),

        // DAWAN (KLUNGKUNG)
        array('kec_id' => 45, 'nama' => 'Besan'),
        array('kec_id' => 45, 'nama' => 'Dawan Kaler'),
        array('kec_id' => 45, 'nama' => 'Dawan Klod'),
        array('kec_id' => 45, 'nama' => 'Gunaksa'),
        array('kec_id' => 45, 'nama' => 'Kampung Kusamba'),
        array('kec_id' => 45, 'nama' => 'Kusamba'),
        array('kec_id' => 45, 'nama' => 'Paksebali'),
        array('kec_id' => 45, 'nama' => 'Pesinggahan'),
        array('kec_id' => 45, 'nama' => 'Pikat'),
        array('kec_id' => 45, 'nama' => 'Sampalan Klod'),
        array('kec_id' => 45, 'nama' => 'Sampalan Tengah'),
        array('kec_id' => 45, 'nama' => 'Sulang'),

        // KLUNGKUNG (KLUNGKUNG)
        array('kec_id' => 46, 'nama' => 'Akah'),
        array('kec_id' => 46, 'nama' => 'Gelgel'),
        array('kec_id' => 46, 'nama' => 'Jumpai'),
        array('kec_id' => 46, 'nama' => 'Kamasan'),
        array('kec_id' => 46, 'nama' => 'Kampung Gelgel'),
        array('kec_id' => 46, 'nama' => 'Manduang'),
        array('kec_id' => 46, 'nama' => 'Satra'),
        array('kec_id' => 46, 'nama' => 'Selat'),
        array('kec_id' => 46, 'nama' => 'Selisihan'),
        array('kec_id' => 46, 'nama' => 'Semarapura Kaja'),
        array('kec_id' => 46, 'nama' => 'Semarapura Kangin'),
        array('kec_id' => 46, 'nama' => 'Semarapura Kauh'),
        array('kec_id' => 46, 'nama' => 'Semarapura Klod Kangin'),
        array('kec_id' => 46, 'nama' => 'Semarapura Kelod'),
        array('kec_id' => 46, 'nama' => 'Semarapura Tengah'),
        array('kec_id' => 46, 'nama' => 'Tangkas'),
        array('kec_id' => 46, 'nama' => 'Tegak'),
        array('kec_id' => 46, 'nama' => 'Tojan'),

        // NUSA PENIDA (KLUNGKUNG)
        array('kec_id' => 47, 'nama' => 'Batukandik'),
        array('kec_id' => 47, 'nama' => 'Batumadeg'),
        array('kec_id' => 47, 'nama' => 'Batununggul'),
        array('kec_id' => 47, 'nama' => 'Bunga Mekar'),
        array('kec_id' => 47, 'nama' => 'Jungutbatu'),
        array('kec_id' => 47, 'nama' => 'Kampung Toyapakeh'),
        array('kec_id' => 47, 'nama' => 'Klumpu'),
        array('kec_id' => 47, 'nama' => 'Kutampi'),
        array('kec_id' => 47, 'nama' => 'Kutampi Kaler'),
        array('kec_id' => 47, 'nama' => 'Lembongan'),
        array('kec_id' => 47, 'nama' => 'Ped'),
        array('kec_id' => 47, 'nama' => 'Pejukutan'),
        array('kec_id' => 47, 'nama' => 'Sakti'),
        array('kec_id' => 47, 'nama' => 'Sekartaji'),
        array('kec_id' => 47, 'nama' => 'Suana'),
        array('kec_id' => 47, 'nama' => 'Tanglad'),

        //BATURITI(TABANAN)
        array('kec_id' => 48, 'nama' => 'Angseri'),
        array('kec_id' => 48, 'nama' => 'Antapan'),
        array('kec_id' => 48, 'nama' => 'Apuan'),
        array('kec_id' => 48, 'nama' => 'Bangli'),
        array('kec_id' => 48, 'nama' => 'Batunya'),
        array('kec_id' => 48, 'nama' => 'Baturiti'),
        array('kec_id' => 48, 'nama' => 'Candikuning'),
        array('kec_id' => 48, 'nama' => 'Luwus'),
        array('kec_id' => 48, 'nama' => 'Mekarsari'),
        array('kec_id' => 48, 'nama' => 'Perean'),
        array('kec_id' => 48, 'nama' => 'Perean Kangin'),
        array('kec_id' => 48, 'nama' => 'Perean Tengah'),


        //KEDIRI(TABANAN)
        array('kec_id' => 49, 'nama' => 'Abian Tuwung'),
        array('kec_id' => 49, 'nama' => 'Banjar Anyar'),
        array('kec_id' => 49, 'nama' => 'Belalang'),
        array('kec_id' => 49, 'nama' => 'Bengkel Sari'),
        array('kec_id' => 49, 'nama' => 'Beraban'),
        array('kec_id' => 49, 'nama' => 'Buwit'),
        array('kec_id' => 49, 'nama' => 'Cepaka'),
        array('kec_id' => 49, 'nama' => 'Kaba-Kaba'),
        array('kec_id' => 49, 'nama' => 'Kediri'),
        array('kec_id' => 49, 'nama' => 'Nyambu'),
        array('kec_id' => 49, 'nama' => 'Nyitdah'),
        array('kec_id' => 49, 'nama' => 'Pandak Bandung'),
        array('kec_id' => 49, 'nama' => 'Pandak Gede'),
        array('kec_id' => 49, 'nama' => 'Pangkuang Tibah'),
        array('kec_id' => 49, 'nama' => 'Pejaten'),

        //KERAMBITAN(TABANAN)
        array('kec_id' => 50, 'nama' => 'Batuaji'),
        array('kec_id' => 50, 'nama' => 'Baturiti'),
        array('kec_id' => 50, 'nama' => 'Belumbang'),
        array('kec_id' => 50, 'nama' => 'Kelating'),
        array('kec_id' => 50, 'nama' => 'Kerambitan'),
        array('kec_id' => 50, 'nama' => 'Kesiut'),
        array('kec_id' => 50, 'nama' => 'Kukuh'),
        array('kec_id' => 50, 'nama' => 'Meliling'),
        array('kec_id' => 50, 'nama' => 'Pangkung Karung'),
        array('kec_id' => 50, 'nama' => 'Penarukan'),
        array('kec_id' => 50, 'nama' => 'Samsam'),
        array('kec_id' => 50, 'nama' => 'Sembung Gede'),
        array('kec_id' => 50, 'nama' => 'Tibubiyu'),
        array('kec_id' => 50, 'nama' => 'Timpag'),
        array('kec_id' => 50, 'nama' => 'Tista'),

        //MARGA(TABANAN)
        array('kec_id' => 51, 'nama' => 'Baru'),
        array('kec_id' => 51, 'nama' => 'Batannyuh'),
        array('kec_id' => 51, 'nama' => 'Beringkit'),
        array('kec_id' => 51, 'nama' => 'Cau Belayu'),
        array('kec_id' => 51, 'nama' => 'Geluntung'),
        array('kec_id' => 51, 'nama' => 'Kukuh'),
        array('kec_id' => 51, 'nama' => 'Kuwum'),
        array('kec_id' => 51, 'nama' => 'Marga'),
        array('kec_id' => 51, 'nama' => 'Marga Dajan Puri'),
        array('kec_id' => 51, 'nama' => 'Marga Dauh Puri'),
        array('kec_id' => 51, 'nama' => 'Payangan'),
        array('kec_id' => 51, 'nama' => 'Peken'),
        array('kec_id' => 51, 'nama' => 'Petiga'),
        array('kec_id' => 51, 'nama' => 'Selanbawak'),
        array('kec_id' => 51, 'nama' => 'Tegaljadi'),
        array('kec_id' => 51, 'nama' => 'Tua'),

        //PENEBEL(TABANAN)
        array('kec_id' => 52, 'nama' => 'Babahan'),
        array('kec_id' => 52, 'nama' => 'Biaung'),
        array('kec_id' => 52, 'nama' => 'Buruan'),
        array('kec_id' => 52, 'nama' => 'Jatiluwih'),
        array('kec_id' => 52, 'nama' => 'Jegu'),
        array('kec_id' => 52, 'nama' => 'Mengeste'),
        array('kec_id' => 52, 'nama' => 'Penatahan'),
        array('kec_id' => 52, 'nama' => 'Penebel'),
        array('kec_id' => 52, 'nama' => 'Pesagi'),
        array('kec_id' => 52, 'nama' => 'Pitra'),
        array('kec_id' => 52, 'nama' => 'Rejasa'),
        array('kec_id' => 52, 'nama' => 'Riang Gede'),
        array('kec_id' => 52, 'nama' => 'Sangketan'),
        array('kec_id' => 52, 'nama' => 'Senganan'),
        array('kec_id' => 52, 'nama' => 'Tajen'),
        array('kec_id' => 52, 'nama' => 'Tegalinggah'),
        array('kec_id' => 52, 'nama' => 'Tengkudak'),
        array('kec_id' => 52, 'nama' => 'Wongaya Gede'),

        //PUPUAN(TABANAN)
        array('kec_id' => 53, 'nama' => 'Bantiran'),
        array('kec_id' => 53, 'nama' => 'Batungsel'),
        array('kec_id' => 53, 'nama' => 'Belatungan'),
        array('kec_id' => 53, 'nama' => 'Belimbing'),
        array('kec_id' => 53, 'nama' => 'Jelijih Punggang'),
        array('kec_id' => 53, 'nama' => 'Karya Sari'),
        array('kec_id' => 53, 'nama' => 'Kebon Padangan'),
        array('kec_id' => 53, 'nama' => 'Munduk Temu'),
        array('kec_id' => 53, 'nama' => 'Padangan'),
        array('kec_id' => 53, 'nama' => 'Pajahan'),
        array('kec_id' => 53, 'nama' => 'Pujungan'),
        array('kec_id' => 53, 'nama' => 'Pupuan'),
        array('kec_id' => 53, 'nama' => 'Sai'),
        array('kec_id' => 53, 'nama' => 'Sanda'),

        //SELEMADEG BARAT(TABANAN)
        array('kec_id' => 54, 'nama' => 'Angkah'),
        array('kec_id' => 54, 'nama' => 'Antosari'),
        array('kec_id' => 54, 'nama' => 'Bengkel Sari'),
        array('kec_id' => 54, 'nama' => 'Lalang Linggah'),
        array('kec_id' => 54, 'nama' => 'Lumbung'),
        array('kec_id' => 54, 'nama' => 'Lumbung Kauh'),
        array('kec_id' => 54, 'nama' => 'Mundeh'),
        array('kec_id' => 54, 'nama' => 'Mundeh Kangin'),
        array('kec_id' => 54, 'nama' => 'Mundeh Kauh'),
        array('kec_id' => 54, 'nama' => 'Selabih'),
        array('kec_id' => 54, 'nama' => 'Tiying Gading'),

        //SELEMADEG TIMUR(TABANAN)
        array('kec_id' => 55, 'nama' => 'Bantas'),
        array('kec_id' => 55, 'nama' => 'Beraban'),
        array('kec_id' => 55, 'nama' => 'Dalang'),
        array('kec_id' => 55, 'nama' => 'Gadung Sari'),
        array('kec_id' => 55, 'nama' => 'Gadungan'),
        array('kec_id' => 55, 'nama' => 'Gunung Salak'),
        array('kec_id' => 55, 'nama' => 'Mambang'),
        array('kec_id' => 55, 'nama' => 'Megati'),
        array('kec_id' => 55, 'nama' => 'Tangguntiti'),
        array('kec_id' => 55, 'nama' => 'Tegal Mengkeb'),

        //SELEMADEG(TABANAN)
        array('kec_id' => 56, 'nama' => 'Antap'),
        array('kec_id' => 56, 'nama' => 'Bajera'),
        array('kec_id' => 56, 'nama' => 'Bajera Utara'),
        array('kec_id' => 56, 'nama' => 'Berembeng'),
        array('kec_id' => 56, 'nama' => 'Manikyang'),
        array('kec_id' => 56, 'nama' => 'Pupuan Sawah'),
        array('kec_id' => 56, 'nama' => 'Selemadeg'),
        array('kec_id' => 56, 'nama' => 'Serampingan'),
        array('kec_id' => 56, 'nama' => 'Wanagiri'),
        array('kec_id' => 56, 'nama' => 'Wanagiri Kauh'),

        //TABANAN(TABANAN)
        array('kec_id' => 57, 'nama' => 'Bongan'),
        array('kec_id' => 57, 'nama' => 'Buahan'),
        array('kec_id' => 57, 'nama' => 'Dauh Peken'),
        array('kec_id' => 57, 'nama' => 'Dajan Peken'),
        array('kec_id' => 57, 'nama' => 'Delod Peken'),
        array('kec_id' => 57, 'nama' => 'Denbantas'),
        array('kec_id' => 57, 'nama' => 'Gubug'),
        array('kec_id' => 57, 'nama' => 'Sesandan'),
        array('kec_id' => 57, 'nama' => 'Subamia'),
        array('kec_id' => 57, 'nama' => 'Sudimara'),
        array('kec_id' => 57, 'nama' => 'Tunjuk'),
        array('kec_id' => 57, 'nama' => 'Wanasari'),

      ]);
    }
}
